language: r
before_install:
  - tlmgr update --self
  - tlmgr install unicode-math
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
before_script:
- chmod +x ./deployment/_build.sh
- chmod +x ./deployment/_deploy.sh
script:
- travis_wait 45 "./deployment/_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deployment/_deploy.sh

# Containers have 2 CPUs by default. Speed up the build by using both.
# c.f. https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
env:
  global:
  - MAKEFLAGS="-j 2"
